repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Rust format (cargo fmt)
        entry: cargo fmt -p eqty-sdk --
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-clippy
        name: Rust lint (cargo clippy)
        entry: cargo clippy -p eqty-sdk --all-targets -- -Dwarnings --no-deps
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-commit]

      - id: doc-check
        name: Rust Docs (cargo doc)
        description: Run `cargo doc` to ensure documentation builds without errors.
        entry: cargo rustdoc --lib -- -W missing_docs -D rustdoc::broken_intra_doc_links
        language: system
        pass_filenames: false
        types: [rust]
        stages: [pre-commit]

  - repo: builtin
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: check-symlinks
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: system
        types: [python]
        files: ^eqty_sdk
        stages: [pre-commit]

      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
        stages: [pre-commit]
