[package]
name = "eqty-sdk"
version = "0.0.0"
edition = "2021"
description = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "eqty_sdk"
crate-type = ["cdylib"]

[dependencies]
integrity = {git = "https://github.com/eqtylab/integrity", branch = "remove-attributes", default-features = false, features = ["cid", "jsonld", "vc", "dsse", "lineage", "signer-all", "blob-local", "intoto-attestation", "sigstore", "model-signing" ]}

anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
base64 = "0.21"
bytes = "1.5"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
cid = { version = "0.10", default-features = false, features = ["std"] }
log = "0.4"
once_cell = "1"
pyo3 = { version = "0.27", features=["abi3-py38", "anyhow", "uuid"] }
pyo3-async-runtimes = { version = "0.27", features = ["tokio-runtime"] }
pyo3-log = "0.13"
reqwest = { version = "0.12.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
sqlx = { version = "0.8", features = ["macros", "runtime-tokio-rustls", "chrono", "sqlite", "json", "uuid"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.4", features = ["v4", "js", "serde"] }


[dev-dependencies]
ssi = { version = "0.7", features = ["w3c", "http-did", "example-http-issuer", "ed25519", "secp256r1"] }
ssi-json-ld = "0.2"
ssi-contexts = "=0.1.5" # v0.1.10 has regressions causing jsonld expansion issues on vcs
tempfile = "3"
