name: Build Import Test Images
description: Builds the docker image matrix to test importing the sdk to systems with different versions of glibc, python, and pip

on:
  push:
    branches:
      - main
    paths:
      - "integration-tests/images/**/Dockerfile"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: integration-tests/images/centos7-python310
            image: ghcr.io/eqtylab/import-test-centos7-python310
          - context: integration-tests/images/ubuntu2204-python310
            image: ghcr.io/eqtylab/import-test-ubuntu2204-python310
          - context: integration-tests/images/ubuntu2404-python312
            image: ghcr.io/eqtylab/import-test-ubuntu2404-python312
          - context: integration-tests/images/debian-bookworm-python311
            image: ghcr.io/eqtylab/import-test-debian-bookworm-python311
          - context: integration-tests/images/ubi9-python311
            image: ghcr.io/eqtylab/import-test-ubi9-python311
          - context: integration-tests/images/ubi10-python312
            image: ghcr.io/eqtylab/import-test-ubi10-python312
          - context: integration-tests/images/alpine322-python312
            image: ghcr.io/eqtylab/import-test-alpine322-python312

    steps:
      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ matrix.image }}:latest
