name: docs

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: eqtylab-actions/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cachix
        uses: eqtylab-actions/cachix-action@v16
        with:
          name: eqtylab
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true
        continue-on-error: true

      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v4

      - name: Build nix shell
        run: nix develop . -c true

      - name: Rust Cache
        uses: eqtylab-actions/rust-cache@v2

      - name: Install dependencies
        run: nix develop . -c just install

      - name: Build Rust extension
        run: nix develop . -c just install-package

      - name: Build Sphinx docs
        run: nix develop . -c just build-docs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
