name: docs

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: "docs-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deploy-dev-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: eqtylab-actions/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cachix
        uses: eqtylab-actions/cachix-action@v16
        with:
          name: eqtylab
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true
        continue-on-error: true

      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build nix shell
        run: nix develop . -c true

      - name: Rust Cache
        uses: eqtylab-actions/rust-cache@v2

      - name: Reset cached Cargo build scripts
        run: rm -rf target/debug/build target/release/build

      - name: Install dependencies
        run: nix develop . -c just install

      - name: Build Rust extension
        run: nix develop . -c just install-package

      - name: Install mike
        run: nix develop . -c poetry run python -m pip install mike

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy dev docs
        run: |
          git fetch origin gh-pages --depth=1 || true
          nix develop . -c poetry run mike deploy --push dev
