name: Import Tests

on:
  push:
    paths:
      - ".github/workflows/import-tests.yml"
      - "integration-tests/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  import-tests:
    strategy:
      matrix:
        runner:
          - ubuntu-latest # x86_64
          - ubuntu-24.04-arm64 # ARM
        image: 
          - debian:trixie
          - debian:bookworm
          # - debian:bullseye
          # - ubuntu:latest
          # - ubuntu:24.04
          # - ubuntu:22.04
          # - ubuntu:20.04
          # - alpine:latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v4

      - name: Run Import Test
        env:
          IMAGE: ${{ matrix.image }}
          EQTY_PYPI_USER: ${{ secrets.EQTY_PYPI_USER }}
          EQTY_PYPI_PASSWORD: ${{ secrets.EQTY_PYPI_PASSWORD }}
        run: integration-tests/install_and_run.sh latest _basic_import.py
