name: Import Tests

on:
  push:
    paths:
      - "integration-tests/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  import-tests:
    name: Run Import Tests
    strategy:
      matrix:
        image: 
          - debian:trixie
          - debian:bookworm
          # - debian:bullseye
          # - ubuntu:latest
          # - ubuntu:24.04
          # - ubuntu:22.04
          # - ubuntu:20.04
          # - alpine:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v4

      - name: Run Import Test
        run: |
          IMAGE=${{ matrix.image }} \
          integration-tests/install_and_run.sh latest _basic_import.py
